name: flutter_rainbow_border
description: "Rainbow Border Container"
version: 0.0.1
homepage: https://github.com/Vulpes94/flutter-rainbow-border

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: